ARG BASE_IMAGE_TAG="${BASE_IMAGE_TAG:-latest}"
ARG BASE_IMAGE_REPO="quay.io/rakuos/rakuos-cosmic"

FROM scratch AS ctx
COPY build_files /

FROM ${BASE_IMAGE_REPO}:${BASE_IMAGE_TAG} AS builder
ARG BASE_IMAGE_TAG
ENV BASE_IMAGE_TAG=${BASE_IMAGE_TAG}
ARG RAKUOS_STAGING="0"
ENV RAKUOS_STAGING=${RAKUOS_STAGING}

COPY system_files /

# Esecuzione dello script di build specifico per AMD
RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build-amd.sh && /ctx/post-build.sh && /ctx/post-build-overlay.sh

COPY system_files /

RUN bootc container lint

LABEL containers.bootc=1
